### ISSUE TITLE
Required keys for metadata in load_supervised_dataset don't match documentation or Automated Loan example

### ISSUE THREAD

**Issue by d1lacy** [seldonian-toolkit/Engine#24]
I created a metadata json file in the same way it was done in the automated loan example (with keys 'regime', 'sub_regime', 'columns', 'label_column', and 'sensitive_columns'). I then got key errors when attempting to load the dataset. By changing the keys in my metadata based on the error messages to 'regime', 'sub_regime', 'all_col_names', 'label_col_names', 'sensitive_col_names' the function worked.

**Comment by austinhoag** [comment]
Thanks for pointing this out. Fixed in https://github.com/seldonian-toolkit/Engine/commit/0749a879d58d700f33edb4fb47ecb110af193725
